[phases.build]
cmds = [
    "cp .env.production .env",
    "composer install --optimize-autoloader --no-dev",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[phases.setup]
nixpkgs = ["php83", "php83Packages.composer", "nodejs_18"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
APP_ENV = "production"
LOG_CHANNEL = "stderr"
