[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev"
]

[phases.setup]
nixpkgs = ["php83", "php83Packages.composer", "nodejs_18"]

[start]
cmd = "bash railway-start.sh"

[variables]
APP_ENV = "production"
LOG_CHANNEL = "stderr"
