services:
  - type: web
    name: lapangin-web
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Lapangin
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d3acg3i4d50c73d5m7ag-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: lapangin_db
      - key: DB_USERNAME
        value: lapangin_db_user
      - key: DB_PASSWORD
        value: FuXHGa7obL65CKOwiirklyIavn738Sid
