services:
  - type: web
    name: lapangin-web
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: echo "Using Docker build, skipping npm"
    envVars:
      - key: APP_NAME
        value: Lapangin
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: lapangin-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: lapangin-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: lapangin-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: lapangin-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: lapangin-db
          property: password

databases:
  - name: lapangin-db
    plan: free
    region: singapore
