services:
  - type: web
    name: lapangin-web
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Lapangin
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://lapangin-web-1.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d26absmu2gs73bgapeg-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: lapangin_production
      - key: DB_USERNAME
        value: lapangin_production_user
      - key: DB_PASSWORD
        sync: false


